packages:
  - 'packages/components'
  - 'packages/utils'
  - 'examples'
  - 'docs'

shamefullyHoist: true
autoInstallPeers: true
confirmModulesPurge: false

allowBuilds:
  '@parcel/watcher': true
  es5-ext: true
  esbuild: true
  vue-demi: true
